### ISSUE TITLE
Validation of the extensions list to avoid crash on file opening

### ISSUE THREAD

**Issue by yochananmarqos** [maoschanz/gedit-plugin-markdown_preview#28]
Manjaro GNOME
`python` 3.9.1
`python-markdown` 3.3.3
`webkit2gtk` 2.30.5

```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/markdown_preview/preview.py", line 380, in on_file_changed
    self.on_reload()
  File "/usr/lib/gedit/plugins/markdown_preview/preview.py", line 319, in on_reload
    html_content = self.get_html_from_p3md(unsaved_text)
  File "/usr/lib/gedit/plugins/markdown_preview/preview.py", line 370, in get_html_from_p3md
    html_string = markdown.markdown(unsaved_text, extensions=md_extensions)
  File "/usr/lib/python3.9/site-packages/markdown/core.py", line 386, in markdown
    md = Markdown(**kwargs)
  File "/usr/lib/python3.9/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/lib/python3.9/site-packages/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/lib/python3.9/site-packages/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name
```

**Comment by maoschanz** [comment]
could you provide the result of the command

```sh
gsettings get org.gnome.gedit.plugins.markdown_preview extensions
```
please?

**Comment by yochananmarqos** [comment]
```
['extra', 'toc', 'sane_lists', '']
```

**Comment by maoschanz** [comment]
using the Dconf editor you can remove the empty string at the end of the list, it should fix your crash

i let the issue opened until i implement some way to avoid loading incorrect markdown extensions names

**Comment by yochananmarqos** [comment]
That worked, thanks! I wonder how that happened. This is a relatively fresh install on my new laptop and I never added any custom extensions.
