### ISSUE TITLE
'Document' object has no attribute 'get_short_name_for_display'

### ISSUE THREAD

**Issue by yochananmarqos** [maoschanz/gedit-plugin-markdown_preview#46]
Gedit 44.2 on GNOME 43.2:

```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/markdown_preview/main_container.py", line 356, in on_file_changed
    self._update_file_format()
  File "/usr/lib/gedit/plugins/markdown_preview/main_container.py", line 367, in _update_file_format
    name, extension = recognize_format(document)
  File "/usr/lib/gedit/plugins/markdown_preview/utils.py", line 5, in recognize_format
    name = document.get_short_name_for_display()
AttributeError: 'Document' object has no attribute 'get_short_name_for_display'
```

**Comment by VentGrey** [comment]
I'm able to reproduce this:

```
Traceback (most recent call last):
  File "/home/ventgrey/.local/share/gedit/plugins/markdown_preview/main_container.py", line 356, in on_file_changed
    self.file_format = self.recognize_format()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventgrey/.local/share/gedit/plugins/markdown_preview/main_container.py", line 364, in recognize_format
    name = doc.get_short_name_for_display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'get_short_name_for_display'
Traceback (most recent call last):
  File "/home/ventgrey/.local/share/gedit/plugins/markdown_preview/main_container.py", line 356, in on_file_changed
    self.file_format = self.recognize_format()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventgrey/.local/share/gedit/plugins/markdown_preview/main_container.py", line 364, in recognize_format
    name = doc.get_short_name_for_display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'get_short_name_for_display'
```

**Comment by FerdiScholten** [comment]
https://github.com/maoschanz/gedit-plugin-markdown_preview/issues/52#issuecomment-1525020945

**Comment by y0va** [comment]
This still appears during export on master for which a [PR](https://github.com/maoschanz/gedit-plugin-markdown_preview/pull/54/commits/ed5ee1ca3cc186e6616c34aa96530277df72f402) was supplied.

![grafik](https://github.com/maoschanz/gedit-plugin-markdown_preview/assets/21321805/8e75e834-dc1f-40e0-ad5f-847e91f44420)
